kind: pipeline
name: default

type : docker

steps:

  - name: unit-test parent-pom-base
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn test --file parent-pom-base/pom.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-base/settings.xml
    when:
      branch:
        include:
          - feature/*
          - main
          - develop
      event:
        include:
          - push
          - pull_request

  - name: build-test parent-pom-base
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn clean package --file parent-pom-base/pom.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-base/settings.xml
    when:
      branch:
        include:
          - feature/*
          - main
          - develop
      event:
        include:
          - push
          - pull_request

  - name: publish-snapshot-package parent-pom-base
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-base/settings.xml  --file parent-pom-base/pom.xml
    when:
      branch:
        include:
          - feature/*
          - main
          - develop
      event:
        include:
          - push
          - pull_request

  - name: publish-release-package parent-pom-base
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-base/settings.xml  --file parent-pom-base/pom.xml
    when:
      event: tag


  - name: unit-test parent-pom-rest
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn test -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD -s parent-pom-rest/settings.xml --file parent-pom-rest/pom.xml
    when:
      branch:
        include:
          - feature/*
          - main
          - develop
      event:
        include:
          - push
          - pull_request

  - name: build-test parent-pom-rest
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn clean package --file parent-pom-rest/pom.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-rest/settings.xml
    when:
      branch:
        include:
          - feature/*
          - main
          - develop
      event:
        include:
          - push
          - pull_request

  - name: publish-snapshot-package parent-pom-rest
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-rest/settings.xml  --file parent-pom-rest/pom.xml
    when:
      branch:
        include:
          - feature/*
          - main
          - develop
      event:
        include:
          - push
          - pull_request

  - name: publish-release-package parent-pom-rest
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-rest/settings.xml  --file parent-pom-rest/pom.xml
    when:
      event: tag


  - name: unit-test parent-pom-async
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn test --file parent-pom-async/pom.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-async/settings.xml
    when:
      branch:
        include:
          - feature/*
          - main
          - develop
      event:
        include:
          - push
          - pull_request

  - name: build-test parent-pom-async
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn clean package --file parent-pom-async/pom.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-async/settings.xml
    when:
      branch:
        include:
          - feature/*
          - main
          - develop
      event:
        include:
          - push
          - pull_request

  - name: publish-snapshot-package parent-pom-async
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-async/settings.xml  --file parent-pom-async/pom.xml
    when:
      branch:
        include:
          - feature/*
          - main
          - develop
      event:
        include:
          - push
          - pull_request

  - name: publish-release-package parent-pom-async
    image: maven:3-jdk-11
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-async/settings.xml  --file parent-pom-async/pom.xml
    when:
      event: tag
