kind: pipeline
name: build

type : docker

volumes:
  - name: m2cache
    host:
      path: /var/cache/m2cache
steps:

  - name: build parent-pom-base
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn clean package -DskipTests=true -Dcheckstyle.skip=true --file parent-pom-base/pom.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-base/settings.xml
    when:
      branch:
        include:
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

  - name: publish-snapshot-package parent-pom-base
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-base/settings.xml  --file parent-pom-base/pom.xml
    when:
      branch:
        include:
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

  - name: publish-release-package parent-pom-base
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-base/settings.xml  --file parent-pom-base/pom.xml
    when:
      event: tag

  - name: build parent-pom-rest
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn clean package -DskipTests=true -Dcheckstyle.skip=true --file parent-pom-rest/pom.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-rest/settings.xml
    when:
      branch:
        include:
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

  - name: publish-snapshot-package parent-pom-rest
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-rest/settings.xml  --file parent-pom-rest/pom.xml
    when:
      branch:
        include:
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

  - name: publish-release-package parent-pom-rest
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-rest/settings.xml  --file parent-pom-rest/pom.xml
    when:
      event: tag

  - name: build parent-pom-async-kafka
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn clean package -DskipTests=true -Dcheckstyle.skip=true --file parent-pom-async-kafka/pom.xml -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD  -s parent-pom-async-kafka/settings.xml
    when:
      branch:
        include:
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

  - name: publish-snapshot-package parent-pom-async-kafka
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD -s parent-pom-async-kafka/settings.xml  --file parent-pom-async-kafka/pom.xml
    when:
      branch:
        include:
          - feature/*
          - main
      event:
        include:
          - push
          - pull_request

  - name: publish-release-package parent-pom-async-kafka
    image: maven:3-openjdk-17-slim
    volumes:
      - name: m2cache
        path: /root/.m2
    environment :
      DEPLOYER_USERNAME :
        from_secret : DEPLOYER_USERNAME
      DEPLOYER_PASSWORD :
        from_secret : DEPLOYER_PASSWORD
    commands:
      - mvn deploy -DskipTests=true -Dcheckstyle.skip=true -Ddeployer.username=$DEPLOYER_USERNAME -Ddeployer.password=$DEPLOYER_PASSWORD -s parent-pom-async-kafka/settings.xml  --file parent-pom-async-kafka/pom.xml
    when:
      event: tag
