name : Continuous Integration Check

on :
  push :
    branches : [ master ]
  pull_request :
    branches : [ master ]

jobs :
  build :

    runs-on : ubuntu-latest

    steps :
      - uses : actions/checkout@v2
      - name : Set up JDK 11
        uses : actions/setup-java@v2
        with :
          java-version : '11'
          distribution : 'adopt'
          cache : maven
      - name : Build parent-pom-base
        run : mvn -B clean package --file parent-pom-base/pom.xml
      - name : Publish parent-pom-base
        run : mvn deploy --file parent-pom-base/pom.xml -s $GITHUB_WORKSPACE/parent-pom-base/settings.xml -Ddeployer.username=${{secrets.DEPLOYER_USERNAME}} -Ddeployer.password=${{secrets.DEPLOYER_PASSWORD}}
        env :
          GITHUB_TOKEN : ${{ github.token }}
      - name : Build parent-pom-rest
        run : mvn -B clean package --file parent-pom-rest/pom.xml
      - name : Publish parent-pom-rest
        run : mvn deploy --file parent-pom-rest/pom.xml -s $GITHUB_WORKSPACE/parent-pom-rest/settings.xml -Ddeployer.username=${{secrets.DEPLOYER_USERNAME}} -Ddeployer.password=${{secrets.DEPLOYER_PASSWORD}}
        env :
          GITHUB_TOKEN : ${{ github.token }}
      - name : Build parent-pom-async
        run : mvn -B clean package --file parent-pom-async/pom.xml
      - name : Publish parent-pom-async
        run : mvn deploy --file parent-pom-async/pom.xml -s $GITHUB_WORKSPACE/parent-pom-async/settings.xml -Ddeployer.username=${{secrets.DEPLOYER_USERNAME}} -Ddeployer.password=${{secrets.DEPLOYER_PASSWORD}}
        env :
          GITHUB_TOKEN : ${{ github.token }}
